openapi: 3.0.3
info:
  title: Search Service API
  description: API documentation for search-related operations
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: Local Development Server

paths:
  /search:
    get:
      summary: Search items
      description: Search for items using query, filters, and pagination.
      parameters:
        - name: query
          in: query
          required: false
          schema:
            type: string
          description: Search keyword
        - name: categoryIds
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
            example: ['cat123', 'cat456']
          style: form
          explode: true
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: Successful search
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                  total:
                    type: integer
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/SearchItem'
        '400':
          description: Invalid parameters

  /search/suggestions:
    get:
      summary: Get search suggestions
      parameters:
        - name: query
          in: query
          required: true
          schema: ty
